# Generated by Django 4.0.5 on 2022-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
                ('chat_id', models.IntegerField(verbose_name='Telegram chat ID')),
            ],
        ),
    ]
