# Generated by Django 4.0.5 on 2022-06-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
