# Generated by Django 4.0.5 on 2022-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedimage_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_processed',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Обработанное изображение'),
        ),
    ]
