# Generated by Django 4.0.5 on 2022-06-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadedimage_image_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_processed',
        ),
    ]
