# Generated by Django 4.0.5 on 2022-06-25 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_uploadedimage_image_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='gen_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время обработки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='tg_user',
            field=models.IntegerField(default=None, null=True, verbose_name='Пользователь'),
        ),
    ]
