# Generated by Django 4.0.5 on 2022-06-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dentistadvice_uploadedimage_gen_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-gen_time']},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
