# Generated by Django 4.0.5 on 2022-06-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_uploadedimage_options_uploadedimage_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentistadvice',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
